### ISSUE TITLE
安装macaca-android时报错

### ISSUE THREAD

**Issue by zhaiworld** [macacajs/uiautomator-client#35]
`C:\Users\zhaixirui>npm i macaca-android

> uiautomator-client@1.0.43 install C:\Users\zhaixirui\node_modules\uiautomator-
client
> node ./scripts/build.js

JAVA_HOME is set to D:\Program Files\jdk1.6.0_39
Updated file C:\Users\zhaixirui\node_modules\uiautomator-client\build.xml
Buildfile: C:\Users\zhaixirui\node_modules\uiautomator-client\build.xml
-check-env:
[checkenv] Android SDK Tools Revision 21.1.0
[checkenv] Installed at D:\adt-bundle-windows-x86-20130219\adt-bundle-windows-x8
6-20130219\sdk

-build-setup:
[echo] Resolving Build Target for uiautomator-bootstrap...
[getuitarget] Project Target:   Android 4.2.2
[getuitarget] API level:        17
[echo] ----------
     [echo] Creating output directories if needed...
[mkdir] Created dir: C:\Users\zhaixirui\node_modules\uiautomator-client\bin
[mkdir] Created dir: C:\Users\zhaixirui\node_modules\uiautomator-client\bin\clas
ses
-pre-compile:

compile:
[javac] Compiling 30 source files to C:\Users\zhaixirui\node_modules\uiautomator
-client\bin\classes

[javac] C:\Users\zhaixirui\node_modules\uiautomator-client\src\com\android\uiaut
omator\client\Element.java:3: �Ҳ������
�
    [javac] ���ţ� �� Configurator
    [javac] λ�ã� ������ com.android.uiautomator.core
    [javac] import com.android.uiautomator.core.Configurator;
    [javac]                                    ^
[javac] C:\Users\zhaixirui\node_modules\uiautomator-client\src\com\android\uiaut
omator\client\Element.java:59: �Ҳ�������
    [javac] ���ţ� �� Configurator
    [javac] λ�ã� �� com.android.uiautomator.client.Element
    [javac]             Configurator config = Configurator.getInstance();
    [javac]             ^
    [javac] C:\Users\zhaixirui\node_modules\uiautomator-client\src\com\android\u
iautomator\client\Element.java:59: �Ҳ�������
    [javac] ���ţ� ���� Configurator
    [javac] λ�ã� �� com.android.uiautomator.client.Element
    [javac]             Configurator config = Configurator.getInstance();
    [javac]                                   ^
[javac] C:\Users\zhaixirui\node_modules\uiautomator-client\src\com\android\uiaut
omator\client\Element.java:107: �Ҳ�������
    [javac] ���ţ� ���� pinchIn(int,int)
    [javac] λ�ã� �� com.android.uiautomator.core.UiObject
    [javac]                     element.pinchIn(percent, steps);
    [javac]                            ^
    [javac] C:\Users\zhaixirui\node_modules\uiautomator-client\src\com\android\u
iautomator\client\Element.java:109: �Ҳ�������
    [javac] ���ţ� ���� pinchOut(int,int)
    [javac] λ�ã� �� com.android.uiautomator.core.UiObject
    [javac]                     element.pinchOut(percent, steps);
    [javac]                            ^
    [javac] C:\Users\zhaixirui\node_modules\uiautomator-client\src\com\android\u
iautomator\client\Element.java:119: �Ҳ�������
    [javac] ���ţ� ���� dragTo(int,int,int)
[javac] λ�ã� �� com.android.uiautomator.core.UiObject
[javac]                 element.dragTo(x, y, steps);
    [javac]                    ^
    [javac] C:\Users\zhaixirui\node_modules\uiautomator-client\src\com\android\u
iautomator\client\XmlUtils\AccessibilityNodeInfoDumper.java:46: �Ҳ�������
    [javac] ���ţ� ���� JELLY_BEAN_MR2
    [javac] λ�ã� �� android.os.Build.VERSION_CODES
    [javac]     public static final boolean API_18 = Build.VERSION.SDK_INT >= Bu
ild.VERSION_CODES.JELLY_BEAN_MR2;
    [javac]
                 ^
    [javac] C:\Users\zhaixirui\node_modules\uiautomator-client\src\com\android\u
iautomator\client\XmlUtils\AccessibilityNodeInfoDumper.java:119: �Ҳ�������
    [javac] ���ţ� ���� getViewIdResourceName()
    [javac] λ�ã� �� android.view.accessibility.AccessibilityNodeInfo
    [javac]             serializer.attribute("", "resource-id", safeCharSeqToStr
ing(node.getViewIdResourceName()));
    [javac]
        ^
[javac] C:\Users\zhaixirui\node_modules\uiautomator-client\src\com\android\uiaut
omator\client\cmd\Actions.java:200: �Ҳ�������
    [javac] ���ţ� ���� drag(int,int,int,int,int)
    [javac] λ�ã� �� com.android.uiautomator.core.UiDevice
    [javac]             return device.drag(fromX, fromY, toX, toY, steps);
    [javac]                          ^
    [javac] C:\Users\zhaixirui\node_modules\uiautomator-client\src\com\android\u
iautomator\client\cmd\Alert.java:77: �Ҳ�������
    [javac] ���ţ� ���� checkable(boolean)
    [javac] λ�ã� �� com.android.uiautomator.core.UiSelector
    [javac]                 .checkable(false)
    [javac]                 ^
    [javac] C:\Users\zhaixirui\node_modules\uiautomator-client\src\com\android\u
iautomator\client\cmd\Find.java:114: �Ҳ�������
    [javac] ���ţ� ���� resourceId(java.lang.String)
    [javac] λ�ã� �� com.android.uiautomator.core.UiSelector
    [javac]                     selectors = selectors.resourceId(text);
    [javac]                                          ^
    [javac] ע�⣺C:\Users\zhaixirui\node_modules\uiautomator-client\src\com\androi
d\uiautomator\client\XmlUtils\ReflectionUtils.java ʹ����δ���������ȫ�Ĳ�����
    [javac] ע�⣺Ҫ�˽���ϸ��Ϣ����ʹ�� -Xlint:unchecked ���±��롣
    [javac] 11 ����
BUILD FAILED
D:\adt-bundle-windows-x86-20130219\adt-bundle-windows-x86-20130219\sdk\tools\ant
\uibuild.xml:182: Compile failed; see the compiler error output for details.

Total time: 5 seconds
C:\Users\zhaixirui\node_modules\uiautomator-client\scripts\build.js:177
      throw e;
      ^

Error: build failed
    at ChildProcess.buildProcess.on.code (C:\Users\zhaixirui\node_modules\uiauto
mator-client\scripts\build.js:163:16)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\zhaixirui\pack
age.json'
npm WARN zhaixirui No description
npm WARN zhaixirui No repository field.
npm WARN zhaixirui No README data
npm WARN zhaixirui No license field.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "i" "macaca-android"
npm ERR! node v6.9.2
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE

npm ERR! uiautomator-client@1.0.43 install: `node ./scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the uiautomator-client@1.0.43 install script 'node ./scripts/
build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the uiautomator-client pa
ckage,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./scripts/build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs uiautomator-client
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls uiautomator-client
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\zhaixirui\npm-debug.log

C:\Users\zhaixirui>npm i -g macaca-android
npm WARN deprecated win-spawn@2.0.0: use [cross-spawn](https://github.com/Indigo
United/node-cross-spawn) or [cross-spawn-async](https://github.com/IndigoUnited/
node-cross-spawn-async) instead.
npm WARN deprecated node-uuid@1.4.7: use uuid module instead
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie h
ttps://nodesecurity.io/advisories/130
npm WARN update-linked node_modules\macaca-android\node_modules\assert-plus need
s updating to 0.2.0 from 1.0.0 but we can't, as it's a symlink
npm WARN update-linked node_modules\macaca-android\node_modules\lodash needs upd
ating to 3.10.1 from 4.17.2 but we can't, as it's a symlink
C:\Users\zhaixirui\AppData\Roaming\npm
`-- macaca-android@1.1.15`

在这种情况下执行Python版本的安卓用例就会出现如下问题：
`C:\Users\zhaixirui\PycharmProjects\macaca-test-sample-python\tests>macaca server

webdriver sdk launched
uiautomator-client.js:31:12 [master] pid:10272 uiautomator-bootstrap was not
found in: C:\Users\zhaixirui\AppData\Roaming\npm\node_modules\macaca-android\nod
e_modules.1.0.43@uiautomator-client\bin\uiautomator-bootstrap.jar, please check
your Android ENV
Error: >> uiautomator-client.js:31:12 [master] pid:10272 uiautomator-bootstrap
was not found in: C:\Users\zhaixirui\AppData\Roaming\npm\node_modules\macaca-an
droid\node_modules.1.0.43@uiautomator-client\bin\uiautomator-bootstrap.jar, ple
ase check your Android ENV
at Logger.error (C:\Users\zhaixirui\AppData\Roaming\npm\node_modules\macac
a-android\node_modules.1.0.6@xlogger\lib\xlogger.js:169:9)
at UIAutomator.init (C:\Users\zhaixirui\AppData\Roaming\npm\node_modules\m
acaca-android\node_modules.1.0.43@uiautomator-client\lib\uiautomator-client.js:
31:12)
at UIAutomator.init.next ()
at onFulfilled (C:\Users\zhaixirui\AppData\Roaming\npm\node_modules\macaca
-cli\node_modules\co\index.js:65:19)
at process._tickCallback (internal/process/next_tick.js:103:7)`

请大神帮忙分析原因

**Comment by xudafeng** [comment]
@zhaiworld 社区去找解决办法
