### ISSUE TITLE
Failed at the uiautomator-client@1.1.9 install script 'node ./scripts/build.js'.

### ISSUE THREAD

**Issue by thanksdanny** [macacajs/uiautomator-client#39]
今天更新新版后app-inspector，出现无法使用，于是重新卸载安装app-inspector，安装后启动，提示我缺少‘uiautomator-client’模块，于是就使用npm安装，这时候就出现报错

`
thankdanny:~ thanksdanny$ npm i uiautomator-client -g
npm WARN deprecated win-spawn@2.0.0: use [cross-spawn](https://github.com/IndigoUnited/node-cross-spawn) or [cross-spawn-async](https://github.com/IndigoUnited/node-cross-spawn-async) instead.
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead

> uiautomator-client@1.1.9 install /usr/local/lib/node_modules/uiautomator-client
> node ./scripts/build.js

JAVA_HOME is set to /Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home
*************************************************************************
The "android" command is deprecated.
For manual SDK, AVD, and project management, please use Android Studio.
For command-line tools, use tools/bin/sdkmanager and tools/bin/avdmanager
*************************************************************************
Invalid or unsupported command "create uitest-project -n uiautomator-bootstrap -t android-23 -p ."
Supported commands are:
android list target
android list avd
android list device
android create avd
android move avd
android delete avd
android list sdk
android update sdk
/usr/local/lib/node_modules/uiautomator-client/scripts/build.js:177
      throw e;
      ^

Error: setup failed
    at ChildProcess.createProcess.on.code (/usr/local/lib/node_modules/uiautomator-client/scripts/build.js:133:16)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
npm ERR! Darwin 16.1.0
npm ERR! argv "/usr/local/Cellar/node/7.8.0/bin/node" "/usr/local/bin/npm" "i" "uiautomator-client" "-g"
npm ERR! node v7.8.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1

npm ERR! uiautomator-client@1.1.9 install: `node ./scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the uiautomator-client@1.1.9 install script 'node ./scripts/build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the uiautomator-client package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./scripts/build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs uiautomator-client
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls uiautomator-client
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/thanksdanny/.npm/_logs/2017-04-04T15_02_47_354Z-debug.log
thankdanny:~ thanksdanny$ npm cache clean -f
npm WARN using --force I sure hope you know what you are doing.

`

**Comment by skumar1122** [comment]
I have same issue in my local.

**Comment by xudafeng** [comment]
npm i macaca-android -g
